export const BLOG_PHOTOS_BATCH = 6

export const BLOG_PHOTOS = [
  { order: 54, location: 'Don Toliver', src: '/images/blog-optimized/54 Don Toliver.jpg' },
  { order: 53, location: 'Summerfest', src: '/images/blog-optimized/53 Summerfest.jpg' },
  { order: 52, location: 'More Kobe', src: '/images/blog-optimized/52 More Kobe.jpg' },
  { order: 51, location: 'Graduation', src: '/images/blog-optimized/51 Graduation.jpg' },
  { order: 50, location: 'Graduation', src: '/images/blog-optimized/50 Graduation.jpg' },
  { order: 49, location: 'Getty Center, CA', src: '/images/blog-optimized/49 Getty Center, CA.jpg' },
  { order: 48, location: 'Getty Center, CA', src: '/images/blog-optimized/48 Getty Center, CA.jpg' },
  { order: 47, location: 'Getty Center, CA', src: '/images/blog-optimized/47 Getty Center, CA.jpg' },
  { order: 46, location: 'Getty Center, CA', src: '/images/blog-optimized/46 Getty Center, CA.jpg' },
  { order: 45, location: 'Griffith Observatory, CA', src: '/images/blog-optimized/45 Griffith Observatory, CA.jpg' },
  { order: 44, location: 'San Diego', src: '/images/blog-optimized/44 San Diego.jpg' },
  { order: 43, location: 'Pine Cove, CA', src: '/images/blog-optimized/43 Pine Cove, CA.jpg' },
  { order: 42, location: 'Alpine Valley, WI', src: '/images/blog-optimized/42 Alpine Valley, WI.jpg' },
  { order: 41, location: 'Nashville', src: '/images/blog-optimized/41 Nashville.jpg' },
  { order: 40, location: 'Kobe', src: '/images/blog-optimized/40 Kobe.jpg' },
  { order: 39, location: 'Social Candy, Milwaukee', src: '/images/blog-optimized/39 Social Candy, Milwaukee.jpg' },
  { order: 38, location: 'Colosseum, Italy', src: '/images/blog-optimized/38 Colosseum, Italy.jpg' },
  { order: 37, location: 'Colosseum, Italy', src: '/images/blog-optimized/37 Colosseum, Italy.jpg' },
  { order: 36, location: 'Rome, Italy', src: '/images/blog-optimized/36 Rome, Italy.jpg' },
  { order: 35, location: 'Rome, Italy', src: '/images/blog-optimized/35 Rome, Italy.jpg' },
  { order: 34, location: 'Rome, Italy', src: '/images/blog-optimized/34 Rome, Italy.jpg' },
  { order: 32, location: 'Rome, Italy', src: '/images/blog-optimized/32 Rome, Italy.jpg' },
  { order: 31, location: 'Trevi Fountain, Italy', src: '/images/blog-optimized/31 Trevi Fountain, Italy.jpg' },
  { order: 30, location: 'Vittoriano, Italy', src: '/images/blog-optimized/30 Vittoriano, Italy.jpg' },
  { order: 29, location: 'Atrani, Italy', src: '/images/blog-optimized/29 Atrani, Italy.jpg' },
  { order: 28, location: 'Positano, Italy', src: '/images/blog-optimized/28 Positano, Italy.jpg' },
  { order: 27, location: 'Porto Di Amalfi, Italy', src: '/images/blog-optimized/27 Porto Di Amalfi, Italy.jpg' },
  { order: 26, location: 'Atrani, Italy', src: '/images/blog-optimized/26 Atrani, Italy.jpg' },
  { order: 25.5, location: 'Atrani, Italy', src: '/images/blog-optimized/25.5 Atrani, Italy.jpg' },
  { order: 25, location: 'Atrani, Italy', src: '/images/blog-optimized/25 Atrani, Italy.jpg' },
  { order: 24, location: 'Atrani, Italy', src: '/images/blog-optimized/24 Atrani, Italy.jpg' },
  { order: 23, location: 'Fam', src: '/images/blog-optimized/23 Fam.jpg' },
  { order: 22, location: 'Kensington, London', src: '/images/blog-optimized/22 Kensington, London.jpg' },
  { order: 21, location: 'City Of Westminster, London', src: '/images/blog-optimized/21 City Of Westminster, London.jpg' },
  { order: 20, location: 'Tower Hamlets, London', src: '/images/blog-optimized/20 Tower Hamlets, London.jpg' },
  { order: 19, location: 'Soho, London', src: '/images/blog-optimized/19 Soho, London.jpg' },
  { order: 18, location: 'Gymshark, London', src: '/images/blog-optimized/18 Gymshark, London.jpg' },
  { order: 17, location: 'Gymshark, London', src: '/images/blog-optimized/17 Gymshark, London.jpg' },
  { order: 16, location: 'London', src: '/images/blog-optimized/16 London.jpg' },
  { order: 15, location: 'London', src: '/images/blog-optimized/15 London.jpg' },
  { order: 14, location: 'London', src: '/images/blog-optimized/14 London.jpg' },
  { order: 13, location: 'Ryse', src: '/images/blog-optimized/13 Ryse.jpg' },
  { order: 12, location: 'Lake Louise, Canada', src: '/images/blog-optimized/12 Lake Louise, Canada.jpg' },
  { order: 11, location: 'Lake Louise, Canada', src: '/images/blog-optimized/11 Lake Louise, Canada.jpg' },
  { order: 10, location: 'Lake Louise Canada', src: '/images/blog-optimized/10 Lake Louise Canada.jpg' },
  { order: 9, location: 'Lake Louise, Canada', src: '/images/blog-optimized/9 Lake Louise, Canada.jpg' },
  { order: 8, location: '✞', src: '/images/blog-optimized/8 ✞.jpg' },
  { order: 7, location: '1st Meet, 1st Place', src: '/images/blog-optimized/7 1st Meet, 1st Place.jpg' },
  { order: 6, location: 'La Jolla Shores', src: '/images/blog-optimized/6 La Jolla Shores.jpg' },
  { order: 5, location: 'San Clemente', src: '/images/blog-optimized/5 San Clemente.jpg' },
  { order: 4, location: 'Cactus Jack', src: '/images/blog-optimized/4 Cactus Jack.jpg' },
  { order: 3, location: 'Chicago', src: '/images/blog-optimized/3 Chicago.jpg' },
  { order: 2, location: 'Las Vegas', src: '/images/blog-optimized/2 Las Vegas.jpg' },
  { order: 1, location: 'Hawaii', src: '/images/blog-optimized/1 Hawaii.jpg' },
]
